# Generated by Django 3.0.10 on 2023-07-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230630_2320'),
        ('orders', '0003_auto_20230630_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
            preserve_default=False,
        ),
    ]
